name: CI

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run Lint
        run: ./gradlew lintDebug
      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew test
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

#  static-code-analysis:
#    needs: [unit-test]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v2
#      - name: set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: SonarCloud Scan
#        run: ./gradlew app:sonarqube -Dsonar.login=${{secrets.SONAR_TOKEN}}
#        env:
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  package:
    needs: [unit-test]
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: expense-manager.apk
          path: app/build/outputs/apk/debug/app-debug.apk
#
#  instrumentation-test:
#    needs: [ unit-test ]
#    runs-on: macos-latest
#    steps:
#      - name: checkout the code
#        uses: actions/checkout@v2
#
#      - name: Run espresso tests
#        uses: reactivecircus/android-emulator-runner@v2.27.0
#        with:
#          api-level: 29
#          profile: Nexus 5
#          target: playstore
#          arch: x86_64
#          force-avd-creation: false
#          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
#          disable-animations: false
#          script: ./gradlew connectedCheck
#      - name: Upload test report
#        uses: actions/upload-artifact@v2
#        with:
#          name: instrumentation_test_report
#          path: app/build/reports/androidTests/connected/